# Config
# ========================================================================================

# IMPORTANT: Set the URL of your site.
# Set to https://<username>.github.io when hosting on GitHub Pages
# (unless you are using a custom domain).
url:                   https://piontau.github.io/

# IMPORTANT: Set The "base URL" of your site.
# When your site sits in a subdirectory, set to /<name of directory>
# (with leading /, but without the < >).
# Use the empty string '' otherwise.
# For GitHub project sites, this is usually the name of the project,
# e.g. `/hydejack`.
baseurl:               ''

# Language of your content in 2-letter code, e.g.: en, de.
# You may also provide a location, e.g.: en-us, de_AT.
lang:                  en

# The title of your blog. Used in the sidebar and the browser tab.
title:                 TesT

# A short description (~150 chars) of the page used for the meta description tag.
# Can use markdown, but no more than one paragraph (enforced by `>`)
description:           >
  In 2016, I obtained a M.SC. in Theoretical and Applied Physics at the University of Antananarivo under the supervision of Prof. Raboanary Roland. The same year, I was a Summer Student at the European Organization for Nuclear Research (<a target="_blank" href="https://home.cern/">CERN</a>) working with the LHCb experiment. Afterward, I moved to Cape Town in South Africa where I was awarded a M.Sc. in Mathematical Sciences from <a target="_blank" href="http://www.sun.ac.za/english">Stellenbosch University</a> (2017) followed by a M.Sc. in Theoretical Physics at the <a target="_blank" href="http://www.uct.ac.za/">University of Cape Town</a> (2018) both under the Supervision of Dr. W. A. Horowitz. I am currently a Ph.D. fellow at the <a target="_blank" href="http://phd.fisica.unimi.it/">Department of Physics</a>-<a target="_blank" href="http://www.unimi.it/">University of Milan</a> (Statale) working within the remarkable <a target="_blank" href="http://n3pdf.mi.infn.it/">N3PDF</a> group (in collab. with <a target="_blank" href="http://nnpdf.mi.infn.it/">NNPDF</a>) under the supervision of Prof. Stefano Forte. My area of interests span a wide range of topics in high energy particle physics (in particular, Quantum Chromodynamics or QCD Phenomenology) and machine learning. 

# A shorter description for the sidebar.
tagline:               >
  # "Best Jekyll Theme by a Mile".
  # Open `_config.yml` to edit this text.

# A list of keywords for your blog
keywords:              []

# A (square) logo for your site.
# If provided, it will be shown at the top of the sidebar.
# It also used by the `jekyll-seo-tag` plugin.
logo:                  /assets/icons/icon.png

# This should be the same author as first entry in `_data/authors.yml`.
author:
  name:                Tanjona R. Rabemananjara
  email:               <tanjona.rabemananjara@unimi.it>
  # Used by `jekyll-seo-tag`:
  # twitter:             <username>

# Add links to the sidebar.
menu:
  - title:             Hydejack
    url:               /hydejack/
  - title:             Hyde
    url:               /hyde/
  - title:             About
    url:               /about/
  - title:             Documentation
    url:               /docs/

# Add links to the footer.
# Typically you'll want to link to your cookie- or privacy policy (if appliable), etc..
# legal:
#   - title:             Impress
#     url:               /impress/
#   - title:             Cookies Policy
#     url:               /cookies-policy/

# This text will appear in a `<small>` tag in the footer of every page.
copyright:             © 2018. All rights reserved.

# Format of the permalinks
permalink:             /:categories/:year-:month-:day-:title/

# Pagination configuration (used by the `blog` layout)
paginate:              5
paginate_path:         /blog/page-:num/


# Customizaton
# ========================================================================================

# Sidebar image and theme color of the site.
accent_image:          /assets/img/sidebar-bg.jpg
accent_color:          rgb(79,177,186)

# This is used for the `theme-color` meta tag,
# which changes the background color of the browser UI in certain browsers.
# Defaults to `accent_color`.
theme_color:           rgb(25,55,71)

# The string encoding which fonts to fetch from Google Fonts.
# See: <https://hydejack.com/docs/configuration/>
google_fonts:          Roboto+Slab:400|Noto+Sans:400,400i,700,700i

# The text font. Expects a string that is a valid CSS font-family value.
# To change font-weight, see _sass/variables.scss
font:                  Noto Sans, Helvetica, Arial, sans-serif

# The font used for headings. Expects a string that is a valid CSS font-family value.
# To change font-weight, see _sass/variables.scss
font_heading:          Roboto Slab, Helvetica, Arial, sans-serif

defaults:
  - scope:
      path:            hyde
    values:
      accent_color:    rgb(38,139,210)
      accent_image:
        background:    rgb(32,32,32)
        overlay:       false

  # `jekyll-seo-tag` will mark collection outputs as `BlogPosting`,
  # but we want them to be `WebPage`s:
  - scope:
      type:            projects
    values:
      seo:
        type:          WebPage
  - scope:
      type:            featured_categories
    values:
      seo:
        type:          WebPage
  - scope:
      type:            featured_tags
    values:
      seo:
        type:          WebPage


# 3rd Party Integrations
# ----------------------------------------------------------------------------------------

# Set your Google Analytics id to receive `pageview` events.
# To remove Google Anaylics from your page, remove the line below.
# google_analytics:      UA-XXXXXXXX-X

# Setting a disqus shortname will enable the comment section on
# pages with `comments: true` in the front matter.
# disqus:                <disqus_shortname>

# Setting a tinyletter username will enable the newsletter subscription box.
# tinyletter:            <tinyletter_username>

# Hydejack Settings
# ----------------------------------------------------------------------------------------
# These settings are specific to Hydejack.

hydejack:
  # Configure the order of complementary content on blog posts
  post_addons:         [about, newsletter, related, random]

  # Configure the order of complementary content on project pages
  project_addons:      [about, newsletter, other]

  # If you do not use Google Fonts, set to `true`.
  no_google_fonts:     false

  # Set to `true` if you don't want to show an icon indicating external links
  no_mark_external:    true

  # Set to `true` if third party plugins fail to work with dynamically loaded pages
  no_push_state:       false

  # Set to `true` if you want to disable the drawer
  no_drawer:           false

  # Set to `true` to prevent usage of `hy-img` (lazy-loading images).
  no_img:              false

  # Set to `true` if you do not want parts of the css inlined in <head/>
  # This will increase site build speed dramatically!
  no_inline_css:       false

  # Set to `true` if you don't intend on changing the accent color on a per-page basis.
  # This will increase site build speed!
  no_page_style:       false

  # Code blocks and tables "break" the layout by spanning the full available width.
  # Set this to true if you want them to be the same width as other content.
  no_break_layout:     false

  # Set to `true` if you do not want to expose your resume and projects
  # in machine-readable formats.
  no_structured_data:  false

  # You can set this to `true` if you don't want to set the `theme-color` meta tag,
  # This only affects the meta tag, not the color specified in the app manifest.
  no_theme_color:      false

  # Set to `true` when building with the `--lsi` option
  use_lsi:             false

  # When using Google Analytics, set to `true` to display a cookie notice banner.
  # When enabled, no user-related data will be stored until the user gives consent.
  cookies_banner:      false

  # Set to `true` if you would like to add a "Powered by Hydejack" link in the footer.
  advertise:           false

  # Note that dark mode only works in the PRO version of Hydejack.
  dark_mode:
    # Set to `true` to always use the dark theme.
    always:            false

    # Set to `true` to use the dark theme based on visitors' local time.
    dynamic:           true
    sunrise:           6
    sunset:            18

    # Set to `true` to allow visitors to switch between light and dark mode.
    icon:              true

  # ⚡️ DANGER ZONE ⚡️
  # ----------------
  # This is an _experimental_ feature.
  # Only use if you know what Service Workers are and how they can impact your site!
  offline:
    enabled:           false
    cache_version:     1


# Collections
# ========================================================================================

collections:
  featured_categories:
    permalink:         /:name/
    output:            true

  featured_tags:
    permalink:         /tag-:name/
    output:            true

  projects:
    permalink:         /projects/:path/
    output:            true


# File inclusion/exclusion
# ========================================================================================

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - "*.gemspec"
  - _js
  - _plugins
  - .sass-cache
include:
  - LICENSE.md


# Plugins
# ========================================================================================

plugins:
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings

# Theme
# ---------------------------------------------------------------------------------------

# theme: jekyll-theme-hydejack
# remote_theme: qwtel/hydejack@gem

# SEO Tag
# ---------------------------------------------------------------------------------------

# Where you proof that you own this site (used by jekyll-seo-tag)
# google_site_verification: <verification-id>
# -- or --
# webmaster_verifications:
#   google:              <verification-id>
#   bing:                <verification-id>
#   alexa:               <verification-id>
#   yandex:              <verification-id>

# Used for Twitter cards
# twitter:
#   username:            <shortname>

# Used for Facebook open graph
# facebook:
#   app_id:              <id>
#   publisher:           <id>
#   admins:              <id>

# Used on index and about sites
# social:
#   name:                <firstname> <lastname>
#   links:
#     - https://twitter.com/<username>
#     - https://github.com/<username>


# Other Plugins
# ---------------------------------------------------------------------------------------

optional_front_matter:
  remove_originals:    true

readme_index:
  remove_originals:    true
  with_frontmatter:    true

relative_links:
  collections:         true

titles_from_headings:
  strip_title:         true
  collections:         true

kramdown:
  footnote_backlink:   '&#x21a9;&#xfe0e;'
  math_engine:         mathjax
  math_engine_opts:
    preview:           true
    preview_as_code:   true

compress_html:
  comments:            ["<!-- ", " -->"]
  clippings:           all
  endings:             all
  ignore:
    envs:              [development]

sass:
  style:               compressed
